### ISSUE TITLE
[Bug] Sky Sweeper doesn't seem to work on sand underwater

### ISSUE THREAD

**Issue by AllieWade** [Direwolf20-MC/JustDireThings#41] opened 2024-04-18 18:33 UTC
Using a Ferricore shovel with Sky Sweeper enabled, sand above the mined block isn't mined when underwater. It works on above-water sand, as well as both above- and below-water gravel.

**Comment by Direwolf20-MC** [comment] 2024-04-18 18:53
I just tested it, and it seemed to work ok for me.  Are you sure the tool wasn't disabled when you tried?

**Comment by AllieWade** [comment] 2024-04-18 19:16
I'll check again, huh.

**Comment by AllieWade** [comment] 2024-04-18 19:27
Okay, after checking again the bug persists; the tool is definitely enabled and I double-checked that it still works on land without changing anything. I'm using a ~fairly large custom modpack I just threw together, so it's probably some sort of conflict. I'm including my mod list just in case but I know these can be tricky and I wouldn't expect anybody else to try to replicate my environment. My apologies for not checking in a test environment before reporting.

Mod list: https://pastebin.com/aErPda2S

I might try a binary search later this week if I have time, see if I can track down the problem, but definitely not today and no promises. 💜

**Comment by Direwolf20-MC** [comment] 2024-04-18 20:43
Can you confirm that when the mod is installed alone (By itself) the tool works as you'd expect, just as a confirmation that its definitely some kind of conflict? :)

**Comment by AllieWade** [comment] 2024-04-18 20:56
Sure, I was able to do that real quick. Running the same mod version (0.9.7) and loader version (Neoforge 20.4.231) and no other mods, I was unable to replicate the bug.

**Comment by Direwolf20-MC** [comment] 2024-04-18 21:12
Thanks I’ll close this. If you find out the cause let me know and I’ll see if I can work around it.

**Closed by Direwolf20-MC** 2024-04-18 21:12 UTC
